title: Joshua Oluyemi Owolabi
logo: comp-logo.png
description: IT Network Engineer | ERP Supervisor | Founder, Spectaluzay Technologies (RC: 3662752)
show_downloads: false
theme: jekyll-theme-minimal
